### ISSUE TITLE
Frequent timeouts

### ISSUE THREAD

**Issue by thinkerytim** [damonjones/Vebra-PHP-API-Wrapper#10]
This isn't your problem, but Vebra's webservices are really pretty terrible about reliability. Timeouts are extremely frequent, where the API won't return data in the default 5 seconds allowed by the buzz client.

You can edit the API.php construct method and add a line for `$this->client->setTimeout(30);` or whatever-- but even with a 30 second timeout they are not always reliable. If you ever feel the urge a method to retry would be welcome-- or maybe allow the timeout to be passed into the constructor.

Thanks!

**Comment by mdavis1982** [comment]
@thinkerytim Thanks Tim. Unfortunately, I don't actually use this library that much anymore, so if you wanted to open a PR to add this functionality then I'm sure we would love to review it and get it merged. Thanks

**Comment by cobuso** [comment]
I don't think you'd need to change the library achieve the timeout change, just configure the `BuzzClientCurl` instance before you pass it to the constructor. Something along the lines of:

    $client = new BuzzClientCurl;
    $client->setTimeout(120); // or whatever
    $api = new VebraAPI(
        'feedid',
        'username',
        'password',
        new TokenStorageFile('username', __DIR__.'/tokens/'),
        $client,
        new BuzzMessageFactory()
    );
