### ISSUE TITLE
The title of the API link in README is wrong

### ISSUE THREAD

**Issue by mdavis1982** [damonjones/Vebra-PHP-API-Wrapper#6]
The title of the link to the API spec in the README file currently says version 3, but needs to be updated to reflect the recent changes from @thinkerytim .

@damonjones Can you update please?

**Comment by mdavis1982** [comment]
Also, the link doesn't work for me. @thinkerytim Could you check the link URL and update it to a working link please?

Thanks for your help with this - it's great to see this being used!

**Comment by damonjones** [comment]
Fixed in #7
