### ISSUE TITLE
types

### ISSUE THREAD

**Issue by thinkerytim** [damonjones/Vebra-PHP-API-Wrapper#9]
does the API wrapper support decoding the "types" and "relatedtypes" data? (http://webservices.vebra.com/export/xsd/v8/rightmovetypes.xsd & http://webservices.vebra.com/export/xsd/v8/propertyrelatedtypes.xsd)

There's a bunch of different values, and instead of a straight 1 to 1 mapping they chose to make the propstatus value differ depending on other values in the feed.

**Comment by mdavis1982** [comment]
Hi @thinkerytim... I'm really sorry for the delay. I'm not entirely sure what you're asking, but if you could give me some more detail I can hopefully help you out!

**Comment by thinkerytim** [comment]
Thanks @mdavis1982-- I was wondering if you'd built any kind of helper methods to "decode" the relatedtypes, rightmovetypes, etc. (since your Property model does have methods for `getRmType`, for example, but returns only an integer rather than going to the rightmovetypes.xsd and looking up that value and returning a string). I built a couple helpers for this but they're pretty static, not sure if you'd want to use them or if there's a cleaner way to implement this.
